name: CI - Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64, 386]  # https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run tests
        run: go test -v ./...
    
      - name: Build
        run: |
          GOARCH=${{ matrix.architecture }} GOOS=linux go build -v -o kman-${{ matrix.architecture }} ./cmd/kman/kman.go

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kman-${{ matrix.architecture }}
          path: kman-${{ matrix.architecture }}

